[server]
bind-address=":8080"
mode="release"
rollbar-token=""
rollbar-environment=""

[mdb]
url="postgres://localhost:5432/mdb?sslmode=disable"

[elasticsearch]
url="http://localhost:9200"
docx-folder="/sites/archive-backend/es/mdb-docx/"
soffice-bin="/usr/bin/libreoffice6.0"
parse-docs-bin="/sites/archive-backend/es/parse_docs.py"
cdn-url="http://cdn.archive"
unzip-url="http://localhost/assets/api"

[file_service]
url1="http://files.archive"

[assets_service]
url="http://localhost/assets/api/"

